coverage:
  range: "85...100"
  status:
    project:
      default:
        target: "85%"
        threshold: "1%"
        removed_code_behavior: fully_covered_patch

ignore:
  - packages/book
  - (?s:.*/[^\/]*\.g\.dart.*)\Z
  - (?s:.*/[^\/]*\.freezed\.dart.*)\Z
  - (?s:.*/injection\.config\.dart.*)\Z
  - ^lib/generated_plugin_registrant.dart.*
  - (?s:.*/[^\/]*\.gr\.dart.*)\Z
  - ^lib/presentation/licenses/oss_licenses.dart.*
