name: collaction_book
description: CollAction Widgetbook for UI Components
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  collaction_common:
    path: ../common
  mobile:
    path: ../mobile
  web:
    path: ../web  
  flutter:
    sdk: flutter
  widgetbook_annotation: ^3.0.0-beta.6
  country_codes: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  widgetbook: ^3.0.0-beta.13
  widgetbook_generator: ^3.0.0-beta.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
