name: common
description: CollAction UIs usable across all platforms.
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook: ^2.4.1
  widgetbook_generator: ^2.4.1

flutter:             
                                      