name: collaction_common
description: >
  This package provides a set of reusable widgets that can be used across all platforms. 
  These widgets are designed to simplify and speed up the development process for creating collaction applications in Flutter.
version: 0.0.1
homepage: https://github.com/CollActionteam/collaction_ui
repository: https://github.com/CollActionteam/collaction_ui
issue_tracker: https://github.com/CollActionteam/collaction_ui/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  country_icons: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:             
                                      