name: Publish collaction_common to pub.dev

on:
  create:
    tags:
      - 'common-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish-common:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: 'production'
      working-directory: packages/common/
